name: SChem build and test
on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  run:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: pip install -r requirements.txt
    - run: python -m unittest discover -s tests
      timeout-minutes: 120
      env:
        PYTHONIOENCODING: UTF-8
